[package]
name = "mg-settings-macros"
description = "Help custom derive for mg-settings"
license = "MIT"
repository = "https://github.com/antoyo/mg-settings"
version = "0.0.1"
authors = ["Antoni Boucher <bouanto@zoho.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "^0.3"
syn = "^0.9"
