[package]
name = "mg-settings"
version = "0.1.2"
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["config"]
description = "Parse config files."
license = "MIT"
repository = "https://github.com/antoyo/mg-settings"
documentation = "https://antoyo.github.io/mg-settings/mg_settings/"

[features]
nightly = []

[dependencies]

[dependencies.mg-settings-macros]
path = "mg-settings-macros"
version = "^0.1.0"

[package.metadata.release]
upload-doc = true
